language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0

os:
  - linux
  - osx

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libtool autoconf automake cmake libncurses5-dev g++ pkg-config screen

before_script:
  - bundle exec rake neovim:install

cache:
  apt: true
  directories:
    - vendor/neovim
