language: ruby
sudo: false
dist: trusty

branches:
  only: master

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head

before_install:
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"

env: REPORT_COVERAGE=1
script: bundle exec rake --trace
