language: ruby

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libtool autoconf automake cmake libncurses5-dev g++ pkg-config screen

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

os:
  - linux
  - osx

script: ./ci.sh
