language: ruby
sudo: false

branches:
  only: master

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libtool
      - autoconf
      - automake
      - cmake
      - libncurses5-dev
      - g++
      - pkg-config

env: REPORT_COVERAGE=1
install: bundle install --without development
before_script: bundle exec rake neovim:install
script: travis_retry bundle exec rake
