language: ruby
sudo: false

branches:
  only: master

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0

os:
  - linux
  - osx

cache:
  - apt
  - bundler

before_install:
  - travis_retry eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"

env: REPORT_COVERAGE=1
script: bundle exec rake --trace spec
