language: ruby
sudo: false

branches:
  only: master

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libtool
      - autoconf
      - automake
      - cmake
      - libncurses5-dev
      - g++
      - pkg-config

cache:
  - apt
  - bundler

env: REPORT_COVERAGE=1
script: bundle exec rake --trace spec:ci
